config/routes.rb
Rails.application.routes.draw do
  Healthcheck.routes(self)
  resources :inventories
  resources :warehouses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "warehouses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    audited

    belongs_to :warehouse, optional: true

    before_update :validate_inventory_not_over_warehouse_limit

    validates :product_name, presence: true
    validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 } 
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 } 

    # in metres
    validates :width, presence: true, numericality: { greater_than_or_equal_to: 0 } 
    validates :length, presence: true, numericality: { greater_than_or_equal_to: 0 } 
    validates :height, presence: true, numericality: { greater_than_or_equal_to: 0 } 

    validate :validate_inventory_not_over_warehouse_limit

    def validate_inventory_not_over_warehouse_limit
        if (warehouse_id)
            if (warehouse.current_capacity + amount * (width * length * height) > warehouse.capacity)
                errors.add(:warehouse_id, "does not have enough capacity to accomodate this item")
            end
        end
    end

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
    audited

    has_many :inventory, dependent: :nullify

    # in metres^3
    validates :location, presence: true
    validates :capacity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 } 

    def current_capacity
        dimensions = []
        inventory.each do |item|
            dimensions << item.width * item.length * item.height
        end
        return dimensions.sum
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:product_name, :amount, :price, :width, :length, :height, :warehouse_id)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[ show edit update destroy ]

  # GET /warehouses or /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1 or /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses or /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully created." }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1 or /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully updated." }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1 or /warehouses/1.json
  def destroy
    @warehouse.destroy

    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: "Warehouse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:location, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>
      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>
  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>
  <div class="field">
    <%= form.label :price %>
    $<%= form.text_field :price %>
  </div>

  <%# <h4><em>Note that the following measurements should be in metres</em></h4> %>
  <div class="field">
    <%= form.label :width %>
    <%= form.text_field :width %> m
  </div>
  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length %> m
  </div>
  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %> m
  </div>
  <div class="field">
    <%= form.label :warehouse_id %>
    <%= form.collection_select(:warehouse_id, Warehouse.all, :id, :location) %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<%= link_to 'New Inventory', new_inventory_path %>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Width</th>
      <th>Length</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.product_name %></td>
        <td><%= inventory.amount %></td>
        <td><%= number_to_currency(inventory.price) %></td>
        <td><%= inventory.width %> m</td>
        <td><%= inventory.length %> m</td>
        <td><%= inventory.height %> m</td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @inventory.product_name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @inventory.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@inventory.price) %>
</p>

<p>
  <strong>Width:</strong>
  <%= @inventory.width %> m
</p>

<p>
  <strong>Length:</strong>
  <%= @inventory.length %> m
</p>

<p>
  <strong>Height:</strong>
  <%= @inventory.height %> m
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/_navbar.html.erb
<div style="margin-top: 2rem;">
  <%= link_to "Warehouses", warehouses_path %>
  <%= link_to "Inventory", inventories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvTrack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "layouts/navbar" %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :capacity, "Capacity in metres^3" %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editing Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Show', @warehouse %> |
<%= link_to 'Back', warehouses_path %>

app/views/warehouses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Warehouses</h1>

<%= link_to 'New Warehouse', new_warehouse_path %>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr>
        <td><%= warehouse.location %></td>
        <td><%= warehouse.capacity %></td>
        <td><%= link_to 'Show', warehouse %></td>
        <td><%= link_to 'Edit', edit_warehouse_path(warehouse) %></td>
        <td><%= link_to 'Destroy', warehouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/warehouses/new.html.erb
<h1>New Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @warehouse.location %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @warehouse.capacity %>
</p>

<%= link_to 'Edit', edit_warehouse_path(@warehouse) %> |
<%= link_to 'Back', warehouses_path %>